#!/bin/bash

phrase=$1

echo 

find . -type f -name "*.txt" -print0 | while read -d $'\0' file
do
    LC_CTYPE=C sed 's/\r//g' "$file" | 
        gawk -v RS='' -v ORS='\n\n' -v IGNORECASE=1 "/${phrase}/" | 
        grep -i -E --color "${phrase}|$" && 
        echo "^^^^^^^ $file ^^^^^^^" && echo && echo
done
