#!/bin/bash

path=$2
phrase=$1

echo 

#for file in $(find . -type f -name "$path")
#awk -v variable="$variable" 'tolower($0) ~ /variable/ { print $0 }' shakespeare.txt

#lower=$(echo "$exp" | tr '[:upper:]' '[:lower:]')

find . -type f -name "$path" -print0 | while read -d $'\0' file
do
    LC_CTYPE=C sed 's/\r//g' "$file" | 
        gawk -v RS='' -v ORS='\n\n' -v IGNORECASE=1 "/${phrase}/" | 
        grep -i -E --color "${phrase}|$" && 
        echo "^^^^^^^ $file ^^^^^^^" && echo && echo
done
